### PR TITLE
Added left nav bar and top bar.  Added icons and images. Added favicons.

### PR DESCRIPTION
**Pull request by Ventan00**
Added elements shared by client views

### CODE REVIEW

**Review by pnarozniak — APPROVED** [review]
Ok

**Comment by Ventan00** [comment]
dodano dark-mode

**Review by Patrykoss — COMMENTED** [review]
Ok

**Comment by pnarozniak** [comment]
Wszystko git!

**Review by Patrykoss — COMMENTED** [review]
Ok

**Review by Patrykoss — APPROVED** [review]

**Pull request merged**
